name: trailify
description: Offline-first audit trail for Flutter apps with Firestore sync. Capture API calls, notifications, user actions, auth events, and errors.
version: 1.0.0
repository: https://github.com/ChauCM/trailify
homepage: https://github.com/ChauCM/trailify
topics: [ audit-trail, logger, debugging, firestore ]

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  path: ^1.9.0
  sembast: ^3.7.4
  path_provider: ^2.0.11
  shared_preferences: ^2.5.4
  uuid: ^4.5.1
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
